run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - gofmt
    - goimports

issues:
  exclude-use-default: false
