DROP TABLE IF EXISTS mst.locations CASCADE;
DROP TABLE IF EXISTS mst.kelurahan CASCADE;
DROP TABLE IF EXISTS mst.kecamatan CASCADE;
DROP TABLE IF EXISTS mst.kabupaten CASCADE;
DROP TABLE IF EXISTS mst.province CASCADE;
