// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
	"honda-leasing-api/configs"
	"honda-leasing-api/internal/auth"
	"honda-leasing-api/internal/auth/handler"
	"honda-leasing-api/internal/auth/postgres"
	"honda-leasing-api/internal/catalog"
	handler2 "honda-leasing-api/internal/catalog/handler"
	postgres2 "honda-leasing-api/internal/catalog/postgres"
	"honda-leasing-api/internal/finance"
	handler6 "honda-leasing-api/internal/finance/handler"
	postgres6 "honda-leasing-api/internal/finance/postgres"
	"honda-leasing-api/internal/infrastructure/http"

	"honda-leasing-api/internal/leasing"
	handler3 "honda-leasing-api/internal/leasing/handler"
	postgres3 "honda-leasing-api/internal/leasing/postgres"
	"honda-leasing-api/internal/master"
	handler5 "honda-leasing-api/internal/master/handler"
	postgres5 "honda-leasing-api/internal/master/postgres"
	"honda-leasing-api/internal/middleware"
	"honda-leasing-api/internal/officer"
	handler4 "honda-leasing-api/internal/officer/handler"
	postgres4 "honda-leasing-api/internal/officer/postgres"
)

// Injectors from wire.go:

// InitializeServer establishes the dependency graph and returns the HTTP server
func InitializeServer(db *gorm.DB, cfg *configs.Config) (*http.Server, error) {
	authRepository := postgres.NewAuthRepository(db)
	jwtConfig := ProvideJwtConfig(cfg)
	service := auth.NewService(authRepository, jwtConfig)
	authHandler := handler.NewAuthHandler(service)
	catalogRepository := postgres2.NewCatalogRepository(db)
	catalogService := catalog.NewService(catalogRepository)
	catalogHandler := handler2.NewCatalogHandler(catalogService)
	leasingRepository := postgres3.NewLeasingRepository(db)
	leasingService := leasing.NewService(leasingRepository)
	leasingHandler := handler3.NewLeasingHandler(leasingService)
	officerRepository := postgres4.NewOfficerRepository(db)
	officerService := officer.NewService(officerRepository)
	officerHandler := handler4.NewOfficerHandler(officerService)
	masterRepository := postgres5.NewMasterRepository(db)
	masterService := master.NewService(masterRepository)
	masterHandler := handler5.NewMasterHandler(masterService)
	financeRepository := postgres6.NewFinanceRepository(db)
	financeService := finance.NewService(financeRepository)
	financeHandler := handler6.NewFinanceHandler(financeService)
	handlerFunc := middleware.Auth(jwtConfig)
	server := ProvideServer(cfg, authHandler, catalogHandler, leasingHandler, officerHandler, masterHandler, financeHandler, officerService, financeService, handlerFunc)
	return server, nil
}

// wire.go:

// ConfigProvider provides specific config parts extracted from the global config
var ConfigProviderSet = wire.NewSet(
	ProvideJwtConfig,
)

func ProvideJwtConfig(cfg *configs.Config) configs.JwtConfig {
	return cfg.Jwt
}

var AuthProviderSet = wire.NewSet(postgres.NewAuthRepository, auth.NewService, handler.NewAuthHandler)

var CatalogProviderSet = wire.NewSet(postgres2.NewCatalogRepository, catalog.NewService, handler2.NewCatalogHandler)

var LeasingProviderSet = wire.NewSet(postgres3.NewLeasingRepository, leasing.NewService, handler3.NewLeasingHandler)

var OfficerProviderSet = wire.NewSet(postgres4.NewOfficerRepository, officer.NewService, handler4.NewOfficerHandler)

var MasterProviderSet = wire.NewSet(postgres5.NewMasterRepository, master.NewService, handler5.NewMasterHandler)

var FinanceProviderSet = wire.NewSet(postgres6.NewFinanceRepository, finance.NewService, handler6.NewFinanceHandler)

var MiddlewareProviderSet = wire.NewSet(middleware.Auth)

// Server setup that registers all routes and returns the server instance
func ProvideServer(
	cfg *configs.Config,
	authHTTPHandler *handler.AuthHandler,
	catHandler *handler2.CatalogHandler,
	leasHandler *handler3.LeasingHandler,
	offcHandler *handler4.OfficerHandler,
	masterHTTPHandler *handler5.MasterHandler,
	financeHTTPHandler *handler6.FinanceHandler,
	offcService officer.Service,
	financeService finance.Service,
	authMiddleware gin.HandlerFunc,
) *http.Server {

	offcService.RegisterCallFunction("GeneratePaymentSchedule", financeService.GeneratePaymentSchedule)
	offcService.RegisterCallFunction("CreatePurchaseOrder", financeService.CreatePurchaseOrder)

	srv := http.NewServer(cfg.App.Port, cfg.App.Env)

	srv.Router.Use(middleware.RequestLogger())
	srv.Router.Use(middleware.GlobalRecovery())

	authHTTPHandler.RegisterRoutes(srv.Router, authMiddleware)
	catHandler.RegisterRoutes(srv.Router, authMiddleware)
	leasHandler.RegisterRoutes(srv.Router, authMiddleware, middleware.RoleBasedAccessControl)
	offcHandler.RegisterRoutes(srv.Router, authMiddleware, middleware.RoleBasedAccessControl)
	masterHTTPHandler.RegisterRoutes(srv.Router)
	financeHTTPHandler.RegisterRoutes(srv.Router)

	return srv
}
